stages:
- update_base_images

# updates all base images used by EcoStream services
# only cretae amd64 images for now

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  BASE_IMAGES_REGISTRY: $CI_REGISTRY_IMAGE/base_images
  NODE_IMAGE_NAME: node
  NODE_IMAGE_VERSION: 22.12

update_base_images:
  when: manual
  image: docker:latest
  stage: update_base_images
  services:
  - docker:dind
  script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  - docker pull node:22.12
  - docker tag node:22.12 "$BASE_IMAGES_REGISTRY/$NODE_IMAGE_NAME:$NODE_IMAGE_TAG"
  - docker push "$BASE_IMAGES_REGISTRY/$NODE_IMAGE_NAME:$NODE_IMAGE_TAG"
