stages:
- update_base_images

# updates all base images used by EcoStream services
# only cretae amd64 images for now

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/
  ARCH: amd64
  NODE_IMAGE_NAME: registry.gitlab.com/gkermo/ecostream/base_images/node
  NODE_IMAGE_TAG: 22.12-$ARCH

update_base_images:
  when: manual
  image: docker:latest
  stage: update_base_images
  services:
  - docker:dind
  script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  - docker pull node:22.12
  - docker tag node:22.12 "$NODE_IMAGE_NAME:$NODE_IMAGE_TAG"
  - docker push "$NODE_IMAGE_NAME:$NODE_IMAGE_TAG"
